alter table QUICKSTART_ORDER add constraint FK_QUICKSTART_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references QUICKSTART_CUSTOMER(ID);
create index IDX_QUICKSTART_ORDER_ON_CUSTOMER on QUICKSTART_ORDER (CUSTOMER_ID);
