alter table QUICKSTART_ORDER_LINE add constraint FK_QUICKSTART_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references QUICKSTART_ORDER(ID);
alter table QUICKSTART_ORDER_LINE add constraint FK_QUICKSTART_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references QUICKSTART_PRODUCT(ID);
create index IDX_QUICKSTART_ORDER_LINE_ON_ORDER on QUICKSTART_ORDER_LINE (ORDER_ID);
create index IDX_QUICKSTART_ORDER_LINE_ON_PRODUCT on QUICKSTART_ORDER_LINE (PRODUCT_ID);
